# Generated by Django 5.1.4 on 2024-12-12 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_participant_created_date_participant_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='email',
            field=models.EmailField(default='akalamoyo@gmail.com', max_length=254),
            preserve_default=False,
        ),
    ]
